name: 'Hello World Docker Action'
description: 'Print "Hello World"'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'world'
outputs:
    time:
      description: 'Current time'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    -${{ inputs.who-to-greet }}
